# Generated by Django 4.0.2 on 2023-10-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_attachment_registration_attachment1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
