# Generated by Django 4.0.2 on 2023-10-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_registration_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='applied_for_edit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
