# Generated by Django 4.2.6 on 2023-10-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_category_a'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_a',
            options={'verbose_name': 'Category A', 'verbose_name_plural': 'Category A'},
        ),
    ]
