# Generated by Django 4.2.6 on 2023-10-29 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_remove_category_a_user_category_a_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_a',
            name='user',
        ),
        migrations.AddField(
            model_name='category_a',
            name='users',
            field=models.ManyToManyField(related_name='categories_a', to=settings.AUTH_USER_MODEL),
        ),
    ]
