# Generated by Django 4.2.6 on 2023-10-29 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_category_d_category_c_category_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_b',
            name='users',
        ),
        migrations.RemoveField(
            model_name='category_c',
            name='users',
        ),
        migrations.RemoveField(
            model_name='category_d',
            name='users',
        ),
        migrations.DeleteModel(
            name='Category_A',
        ),
        migrations.DeleteModel(
            name='Category_B',
        ),
        migrations.DeleteModel(
            name='Category_C',
        ),
        migrations.DeleteModel(
            name='Category_D',
        ),
    ]
