# Generated by Django 4.2.6 on 2023-10-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_category_b_users_remove_category_c_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(help_text='member name', max_length=90),
        ),
    ]
