# Generated by Django 4.2.6 on 2023-11-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_registration_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='passport_gonna_expire_in_30_days',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='visa_expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='visa_gonna_expire_in_30_days',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='passport_expiry',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
