# Generated by Django 4.2.6 on 2023-10-29 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(related_name='categories_d', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category D',
                'verbose_name_plural': 'Category D',
            },
        ),
        migrations.CreateModel(
            name='Category_C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(related_name='categories_c', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category C',
                'verbose_name_plural': 'Category C',
            },
        ),
        migrations.CreateModel(
            name='Category_B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(related_name='categories_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category B',
                'verbose_name_plural': 'Category B',
            },
        ),
        migrations.CreateModel(
            name='Category_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(related_name='categories_a', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category A',
                'verbose_name_plural': 'Category A',
            },
        ),
    ]
